package pojo;
// Generated Oct 14, 2021 10:33:07 PM by Hibernate Tools 4.3.1

import dao.UserDao;
import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import presenter.Singleton;




/**
 * TblLog generated by hbm2java
 */
@ManagedBean(name = "log_bean" , eager= true)
@SessionScoped
public class TblLog  implements java.io.Serializable {


     private Integer id;
     private TblWallet tblWallet;
     private String type;
     private int amount;
     private String date;

    public TblLog() {
    }

    public TblLog(TblWallet tblWallet, String type, int amount, String date) {
       this.tblWallet = tblWallet;
       this.type = type;
       this.amount = amount;
       this.date = date;
    }
    
    public List<TblLog> getLogs(){
        UserDao dao = new UserDao();
        List<TblLog> list = dao.getLogs(Singleton.userId);
        return list;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public TblWallet getTblWallet() {
        return this.tblWallet;
    }
    
    public void setTblWallet(TblWallet tblWallet) {
        this.tblWallet = tblWallet;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public int getAmount() {
        return this.amount;
    }
    
    public void setAmount(int amount) {
        this.amount = amount;
    }
    public String getDate() {
        return this.date;
    }
    
    public void setDate(String date) {
        this.date = date;
    }




}


