package pojo;
// Generated Oct 14, 2021 10:33:07 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TblWallet generated by hbm2java
 */
public class TblWallet  implements java.io.Serializable {


     private Integer id;
     private TblUser tblUser;
     private int balance;
     private String type;
     private Set tblLogs = new HashSet(0);

    public TblWallet() {
    }

	
    public TblWallet(TblUser tblUser, int balance, String type) {
        this.tblUser = tblUser;
        this.balance = balance;
        this.type = type;
    }
    public TblWallet(TblUser tblUser, int balance, String type, Set tblLogs) {
       this.tblUser = tblUser;
       this.balance = balance;
       this.type = type;
       this.tblLogs = tblLogs;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public TblUser getTblUser() {
        return this.tblUser;
    }
    
    public void setTblUser(TblUser tblUser) {
        this.tblUser = tblUser;
    }
    public int getBalance() {
        return this.balance;
    }
    
    public void setBalance(int balance) {
        this.balance = balance;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public Set getTblLogs() {
        return this.tblLogs;
    }
    
    public void setTblLogs(Set tblLogs) {
        this.tblLogs = tblLogs;
    }




}


